import { Collection } from "../Context";

export const presetCollections_old: Collection[] = [
  // {
  //   name: "All",
  //   id: "preset-collecction-all",
  //   categoriez: [],
  // },
  {
    name: "Essen und Trinken",
    id: "preset-collecction1",
    categoriez: [
      "Babynahrung",
      "Französische Nachspeise",
      "Hochprozentiger Cocktail",
      "Vegetarischer Burger",
      "Türkische Vorspeise",
      "Indisches Hauptgericht",
      "Italienische Weinsorte",
      "Getreidesorte",
      "Müsli-Zutat",
      "Teesorte",
      "Joghurtsorte",
      "Tropische Frucht",
      "Afrikanisches Gemüse",
      "Kaffeesorte aus Mittelamerika",
      "Backzutat",
      "Giftige Chemikalie",
      "Energydrink",
      "Katzenfutter",
      "Salzige Knabberei",
      "Schokoriegel",
    ],
  },
  {
    name: "Adults only",
    id: "preset-collecction2",
    categoriez: [
      "Titel eines Erotikfilms",
      "Anderes Wort für 'Samenbank'",
      "Potenzmittel",
      "Onlineshop für Seyspielzeug",
      "Anderes Wort für 'Kiffen'",
      "Erogene Zone",
      "Anderes Wort für 'Aphrodisiakum'",
      "Anderes Wort für 'Penisverlängerung'",
      "Geschieht vor allem nachts",
      "Synthetische Partydroge",
      "Gerät beim Urologen",
      "Kosewort für 'Busen'",
      "Stellung aus dem Kamasutra",
      "Anderes Wort für 'Vibrator'",
      "Kondom-Marke",
      "Erotik-Sender",
      "Zwielichtige Gestalt",
      "Anderes Wort für 'G-Punkt'",
      "Anderes Wort für 'Hoden'",
      "Künstlername einer Domina",
      "Etwas sehr Feuchtes",
      "Damenunterwäsche",
      "Anderes Wort für 'verrückt'",
      "Fruchtbarkeitsritual",
    ],
  },
  {
    name: "Synonyme/ Andere Sprachen",
    id: "preset-collecction3",
    categoriez: [
      "Befehl beim Hundeschlittenrennen",
      "Anderes Wort für 'Rülpser'",
      "Anderes Wort für 'Speeddating'",
      "Anderes Wort für 'Kannibale'",
      "Anderes Wort für 'Blasenschwäche'",
      "Anderes Wort für 'Übergewicht'",
      "Lateinischer Name für Gesäßmuskel",
      "Isländisch für 'Ruhe!'",
      "Anderes Wort für 'Zäpfchen'",
      "Anderes Wort für 'Hautausschlag'",
      "Anderes Wort für 'Wespentaille'",
      "Anderes Wort für 'Rotznase'",
      "Anderes Wort für 'Kakerlake'",
      "'Feuer' in der Sprache der Neandertaler",
      "Polnischer Kraftausdruck",
      "Beleidigung auf Portugiesisch",
      "Anderes Wort für 'Quatsch'",
      "Anderes Wort für 'Furz'",
      "'Prost!' auf Bulgarisch",
      "Hebräischer Gruß",
      "Militärischer Befehl",
      "Begriff aus der Seemannssprache",
      "Chinesisches Wort für 'Fahrrad'",
      "'Schnee' in der Sprache der Inuit",
      "Anderes Wort für 'Liebesnacht'",
    ],
  },
  {
    name: "Pflanzen, Tiere, Biologie",
    id: "preset-collecction4",
    categoriez: [
      "Gefährliches Monster",
      "Insektenart",
      "Gefährliche Spinnenart",
      "Tierlaut",
      "Anderes Wort für 'Dung'",
      "Rufname eines Kampfhundes",
      "Wohlriechende Pflanze",
      "Australisches Beuteltier",
      "Tiefseebewohner",
      "Hunderasse",
      "Schlangenart",
      "Stachelige Wüstenpflanze",
      "Gefährliche Krankheit",
      "Glückshormon",
      "Gefährliches Gift",
    ],
  },
  {
    name: "Orte",
    id: "preset-collection5",
    categoriez: [
      "Planet",
      "Spanische Landschaft",
      "Hauptstadt des Pluto",
      "Nördlichste Stadt der Erde",
      "Kneipe auf der Reeperbahn",
      "Südsee-Insel",
      "Neu entdeckter Berg im Himalaya",
    ],
  },
  {
    name: "Dinge & Bezeichnungen",
    id: "preset-collection6",
    categoriez: [
      "Küchengerät",
      "Shampoo",
      "Mittelalterliches Folterinstrument",
      "Bestandteil eines Autos",
      "Kartenspiel",
      "Seltenes Metall",
      "Videospiel",
      "Der neueste technische Gimmick",
      "Kuscheltier",
      "Putzmittel",
      "Steinzeitliche Werkzeug",
      "Fernsehzeitung",
      "Landwirtschaftliches Gerät",
      "Männermagazin",
      "Musikinstrument",
      "Lustiges Partyspiel",
      "Ungewöhnliches Spielzeug",
      "Starkes Stück!",
      "Etwas, was Skandinavier besonders mögen",
      "Attraktion eines Vergnügungsparks",
      "Ungeliebtes Schulfach",
      "Französisches Liebeslied",
      "Neuartige Suchmaschine",
      "Toilettenpapier-Marke",
      "Flirt-App",
      "Marke für Babywindeln",
      "Neuer Streaming-Anbieter",
      "TV-Quiz",
      "Titel eines Science-Fiction-Films",
    ],
  },
  {
    name: "Persönlichkeiten und Namen",
    id: "preset-collection7",
    categoriez: [
      "Boygroup",
      "James-Bond-Bösewicht",
      "Name einer Motorrad-Gang",
      "Gestalt aus der Bibel",
      "Abfälliges Wort für 'Politiker'",
      "Name von Tarzans Lieblingsaffen",
      "Ägyptischer Pharao",
      "Gestalt aus der griechischen Mythologie",
      "Noramerikanischer Stamm",
      "Indische Göttin",
      "Österreichischer Volksmusiker",
      "Dschungelbewohner",
      "Comicfigur",
      "Superheld",
      "Name für die Zahnfee",
      "Bezeichnung für einen miesen Lehrer",
      "Abfälliger Ausdruck für Versicherungsvertreter",
      "Spitzname für Vladimir Putin",
      "Germanische Gottheit",
      "Heavy-Metal-Band",
      "Kosename für den/die Liebste/n",
      "Stamm in Zentralafrika",
      "Charakter aus 'Star Wars'",
      "Figur aus 'Herr der Ringe'",
      "Finnischer Skisportler",
      "Indiostamm am Amazonas",
      "Außerirdisches Volk",
      "Römischer Kaiser",
      "Westernheld",
      "Beschäftigter einer Recycling-Firma",
      "Ungezogenes Kind",
    ],
  },
  {
    name: "Hat bestimmte Merkmale",
    id: "preset-collection8",
    categoriez: [
      "Etwas typisch Rotes",
      "Etwas Großes",
      "Etwas kleines",
      "Etwas zum Streicheln",
      "Etwas aus Gummi",
      "Macht Löcher",
      "Etwas sehr Teures",
      "Ist groß und gefährlich",
      "Hat Flecken",
      "Vorsicht! Ein/e ...",
      "Wie niedlich! Ein/e ...",
      "Dumm wie Brot",
    ],
  },
  {
    name: "Macht man",
    id: "preset-collection7",
    categoriez: [
      "Sportart für Zombies",
      "Neue Ballsportart",
      "Tanzstil",
      "Japanische Kampfsportart",
    ],
  },
];
