import { Collection } from "../Context";

export const presetCollections: Collection[] = [
  {
    name: "All",
    id: "preset-collecction-all",
    categoriez: [
      "cat1.1",
      "cat1.2",
      "cta1.3",
      "catloremsbnsid",
      "catloremsbnsid",
      "cat",
      "cat",
      "catloremsbnsid",
    ],
  },
  {
    name: "Essen und Trinken",
    id: "preset-collecction1",
    categoriez: [
      "Babynahrung",
      "Französische Nachspeise",
      "Hochprozentiger Cocktail",
      "Vegetarischer Burger",
      "Türkische Vorspeise",
      "Indisches Hauptgericht",
      "Italienische Weinsorte",
      "Getreidesorte",
      "Müsli-Zutat",
      "Teesorte",
      "Joghurtsorte",
      "Tropische Frucht",
      "Afrikanisches Gemüse",
      "Kaffeesorte aus Mittelamerika",
      "Backzutat",
      "Giftige Chemikalie",
      "Energydrink",
      "Katzenfutter",
      "Salzige Knabberei",
      "Schokoriegel",
    ],
  },
  {
    name: "Adults only",
    id: "preset-collecction2",
    categoriez: [
      "Titel eines Erotikfilms",
      "Anderes Wort für 'Samenbank'",
      "Potenzmittel",
      "Onlineshop für Seyspielzeug",
      "Anderes Wort für 'Kiffen'",
      "Erogene Zone",
      "Anderes Wort für 'Aphrodisiakum'",
      "Anderes Wort für 'Penisverlängerung'",
      "Geschieht vor allem nachts",
      "Synthetische Partydroge",
      "Gerät beim Urologen",
      "Kosewort für 'Busen'",
      "Stellung aus dem Kamasutra",
      "Anderes Wort für 'Vibrator'",
      "Kondom-Marke",
      "Erotik-Sender",
      "Zwielichtige Gestalt",
      "Anderes Wort für 'G-Punkt'",
      "Anderes Wort für 'Hoden'",
      "Künstlername einer Domina",
      "Etwas sehr Feuchtes",
      "Damenunterwäsche",
      "Anderes Wort für 'verrückt'",
    ],
  },
  {
    name: "Synonyme",
    id: "preset-collecction3",
    categoriez: [
      "Befehl beim Hundeschlittenrennen",
      "Anderes Wort für 'Rülpser'",
      "Anderes Wort für 'Speeddating'",
      "Anderes Wort für 'Kannibale'",
      "Anderes Wort für 'Blasenschwäche'",
      "Anderes Wort für 'Übergewicht'",
      "Lateinischer Name für Gesäßmuskel",
      "Isländisch für 'Ruhe!'",
      "Anderes Wort für 'Zäpfchen'",
      "Anderes Wort für 'Hautausschlag'",
      "Anderes Wort für 'Wespentaille'",
      "Anderes Wort für 'Rotznase'",
      "Anderes Wort für 'Kakerlake'",
      "'Feuer' in der Sprache der Neandertaler",
      "Polnischer Kraftausdruck",
      "Beleidigung auf Portugiesisch",
      "Anderes Wort für 'Quatsch'",
      "Anderes Wort für 'Furz'",
      "'Prost!' auf Bulgarisch",
      "Hebräischer Gruß",
      "Militärischer Befehl",
      "Begriff aus der Seemannssprache",
      "Chinesisches Wort für 'Fahrrad'",
      "'Schnee' in der Sprache der Inuit",
    ],
  },
  {
    name: "Pflanzen und Tiere",
    id: "preset-collecction4",
    categoriez: [
      "Gefährliches Monster",
      "Insektenart",
      "Gefährliche Spinnenart",
      "Tierlaut",
      "Anderes Wort für 'Dung'",
      "Rufname eines Kampfhundes",
      "Wohlriechende Pflanze",
      "Australisches Beuteltier",
      "Tiefseebewohner",
      "Hunderasse",
      "Schlangenart",
      "Stachelige Wüstenpflanze",
    ],
  },
  {
    name: "Orte",
    id: "preset-collection5",
    categoriez: [
      "Planet",
      "Spanische Landschaft",
      "Hauptstadt des Pluto",
      "Nördlichste Stadt der Erde",
      "Kneipe auf der Reeperbahn",
      "Südsee-Insel",
      "Neu entdeckter Berg im Himalaya",
    ],
  },
  {
    name: "Dinge",
    id: "preset-collection6",
    categoriez: [
      "Küchengerät",
      "Shampoo",
      "Mittelalterliches Folterinstrument",
      "Bestandteil eines Autos",
      "Kartenspiel",
      "Seltenes Metall",
      "Videospiel",
      "Der neueste technische Gimmick",
      "Kuscheltier",
      "Putzmittel",
      "Steinzeitliche Werkzeug",
      "Fernsehzeitung",
      "Landwirtschaftliches Gerät",
      "Männermagazin",
      "Musikinstrument",
      "Lustiges Partyspiel",
    ],
  },
];
