import { Collection } from "../Context";

export const presetCollections: Collection[] = [
  {
    name: "Essen und Trinken",
    id: "preset-collecction1",
    categoriez: [
      "Gewürz",
      "Kann man im Fast-Food-Laden bestellen",
      "Verkauft der Kiosk an der Ecke",
      "Findet man im Süßigkeitenregal",
      "Zutat in einem Eintopf",
      "Sollte im Gefrierer gelagert werden",
      "Passt auf ein Sandwich",
      "Salzige Knabberei",
      "Alkoholisches Getränk",
    ],
  },
  {
    name: "Adults only",
    id: "preset-collecction2",
    categoriez: [
      "Geschenk für ein Date",
      "Ist für militärische Zwecke einsetzbar",
      "Name für ein Sextoy",
      "Name einer Drag-Queen",
      "Anderes Wort für Penis",
      //
      "Ist vor allem nachts aktiv / im Gebrauch",
      "Von solchen Dingen kann man süchtig werden",
      "Fasziniert Männer",
      "Brauchen Frauen häufiger als Männer",
      "Damit/ Dadurch wurden schon etliche Menschen ums Leben gebracht",
    ],
  },
  {
    name: "Synonyme",
    id: "preset-collecction3",
    categoriez: [],
  },
  {
    name: "Pflanzen und Tiere",
    id: "preset-collecction4",
    categoriez: [
      "Würde ein Krokodil essen",
      "Wächst an Bäumen",
      "Lebt im Urwald",
      "Lebt in der Wüste",
      "Ist am Meeresgrund zu finden",
    ],
  },
  {
    name: "Orte",
    id: "preset-collecction5",
    categoriez: [
      "Ist im Süden sehr beliebt",
      "Stammt aus Afrika",
      "Stammt aus Australien",
      "Stammt aus Asien",
      "Typisch Hollywood",
      "Ort in Mittelerde",
    ],
  },
  {
    name: "Dinge",
    id: "preset-collecction6",
    categoriez: [
      "IKEA-Möbelstück",
      "Findet man bei Harry-Potter",
      "Findet man auf einer Werkbank",
      "Findet man in einer Federtasche",
      "Teil eines klassischen Wild-West-Films",
      "Erinnert ans Krankenhaus",
      "Sherlock Holmes hätte Verwendung dafür",
      "Kann man in einer Apotheke kaufen",
      "Ist im Handgepäck verboten",
      "Findet man am Boden der Tiefsee",
      "Bewegt sich im Straßenverkehr",
      //
      "Wird in Vorlesungen behandelt",
      "Ist öfters in Badezimmern oder Toiletten",
      "Ist dem Schneemann eine Zier",
      "Kann man in einem Supermarkt kaufen",
      "Ist oft in Büros",
      "Sieht man häufig am Badestrand",
      "Findet vor allem im Winter Verwendung",
      "Ist häufig im Wohn- oder Schlafzimmer",
    ],
  },
  {
    name: "Persönlichkeiten und Namen",
    id: "preset-collecction7",
    categoriez: [
      "Name einer Fast-Food-Kette",
      "Deutsche(r) Politiker(in)",
      "Name eines Orks",
      "Make-Up Marke",
    ],
  },
  {
    name: "Hat bestimmte Merkmale",
    id: "preset-collecction8",
    categoriez: [
      "Eine Maßeinheit",
      "Lässt sich verbrennen",
      "Kann man am Himmel sehen",
      "Ist häufig im Wasser",
      //
      "Hat Deckel oder Verschluss",
      "Besteht aus Wolle, Tuch oder Stoff",
      "Fühlt sich glatt an",
      "Besteht zu großen Teilen aus Stein oder Glas",
      "Ist im Wesentlichen flach",
      "Ist rund",
      "Besteht größtenteils aus Papier oder Pappe",
      "Schwimmt",
      "Besteht zur Hauptsache aus Holz",
      "Hat Beine",
      "Ist schwer. Sehr schwer.",
      "Ist ohne Elektrizität wenig brauchbar",
      "Versinkt im Wasser",
    ],
  },
];
